exports.seed = async function(knex) {
  // Deletes ALL existing entries
  await knex('product_images').del()
  const product_ids = await knex('products').pluck('id');
  await knex('product_images').insert([
    { image_url: 'https://res.cloudinary.com/ducbh1hqd/image/upload/v1655582748/product-images/weipa-id1_eeg6gl.jpg', 
      image_name: 'product-images/weipa-id1_eeg6gl', 
      product_id: product_ids[0] },
    { image_url: 'https://res.cloudinary.com/ducbh1hqd/image/upload/v1655582748/product-images/mole-id2_wsh0xs.jpg', 
      image_name: 'product-images/mole-id2_wsh0xs', 
      product_id: product_ids[1] },
    { image_url: 'https://res.cloudinary.com/ducbh1hqd/image/upload/v1655582747/product-images/miso-id3_egguky.webp', 
      image_name: 'product-images/miso-id3_egguky', 
      product_id: product_ids[2] },
    { image_url: 'https://res.cloudinary.com/ducbh1hqd/image/upload/v1655582749/product-images/charsiu-id4_bwzula.webp', 
      image_name: 'product-images/charsiu-id4_bwzula', 
      product_id: product_ids[3] },
    { image_url: 'https://res.cloudinary.com/ducbh1hqd/image/upload/v1655582748/product-images/reynaverde-id5_c5u4mi.jpg', 
      image_name: 'product-images/reynaverde-id5_c5u4mi', 
      product_id: product_ids[4] },
    { image_url: 'https://res.cloudinary.com/ducbh1hqd/image/upload/v1655582748/product-images/sesameoil-id6_kkeweg.jpg', 
      image_name: 'product-images/sesameoil-id6_kkeweg',
      product_id: product_ids[5] },
    { image_url: 'https://res.cloudinary.com/ducbh1hqd/image/upload/v1655582748/product-images/bragg-id7_qmfud5.webp',
      image_name: 'product-images/bragg-id7_qmfud5', 
      product_id: product_ids[6] },
    { image_url: 'https://res.cloudinary.com/ducbh1hqd/image/upload/v1655582747/product-images/dryoregano-id8_jc2vj3.webp',
      image_name: 'product-images/dryoregano-id8_jc2vj3', 
      product_id: product_ids[7] },
    { image_url: 'https://res.cloudinary.com/ducbh1hqd/image/upload/v1655582748/product-images/thyme-id9_fy42cj.jpg',
      image_name: 'product-images/thyme-id9_fy42cj', 
      product_id: product_ids[8] },
    { image_url: 'https://res.cloudinary.com/ducbh1hqd/image/upload/v1655582748/product-images/anchopowder-id10_gsk6qz.jpg',
      image_name: 'product-images/anchopowder-id10_gsk6qz',
      product_id: product_ids[9] },
    { image_url: 'https://res.cloudinary.com/ducbh1hqd/image/upload/v1655582748/product-images/yuzushichi-id11_fbubkz.webp',
      image_name: 'product-images/yuzushichi-id11_fbubkz',
      product_id: product_ids[10] },
    { image_url: 'https://res.cloudinary.com/ducbh1hqd/image/upload/v1655582747/product-images/heinzket-id12_n6gykf.jpg', 
      image_name: 'product-images/heinzket-id12_n6gykf',
      product_id: product_ids[11] },
    { image_url: 'https://res.cloudinary.com/ducbh1hqd/image/upload/v1655582747/product-images/hpsauce-id13_g2lvoc.jpg',
      image_name: 'product-images/hpsauce-id13_g2lvoc',
      product_id: product_ids[12] },
    { image_url: 'https://res.cloudinary.com/ducbh1hqd/image/upload/v1655582748/product-images/yumenishiki-id14_dkrynz.webp', 
      image_name: 'product-images/yumenishiki-id14_dkrynz',
      product_id: product_ids[13] },
    { image_url: 'https://res.cloudinary.com/ducbh1hqd/image/upload/v1655582747/product-images/millet-id15_du4idu.webp', 
      image_name: 'product-images/millet-id15_du4idu',
      product_id: product_ids[14] },
    { image_url: 'https://res.cloudinary.com/ducbh1hqd/image/upload/v1655582747/product-images/kidneybeans-id16_spndnz.jpg', 
      image_name: 'product-images/kidneybeans-id16_spndnz',
      product_id: product_ids[15] },
    { image_url: 'https://res.cloudinary.com/ducbh1hqd/image/upload/v1655582748/product-images/pintobeans-id17_hm4pkn.webp', 
      image_name: 'product-images/pintobeans-id17_hm4pkn',
      product_id: product_ids[16] },
  ]);
};
